hyperskill_project:
  id: 138
  ide_files: https://stepik.org/media/attachments/lesson/432858/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Thu, 01 Jan 1970 00:00:00 UTC
stages:
- id: 735
  step: 11364
  is_completed: false
- id: 736
  step: 11365
  is_completed: false
- id: 737
  step: 11366
  is_completed: false
- id: 738
  step: 11367
  is_completed: false
- id: 739
  step: 11368
  is_completed: false
